### ISSUE TITLE
logEvent hook causes effects to trigger

### ISSUE THREAD

**Issue by ljmerza** [koblas/react-amplitude-hooks#12]
I dont think the useAmplitude is returning the same function reference because using logEvent inside useEffect is causing the effect to trigger on each render of the parent component. A simple example:

```
function App(){
  const { logEvent } = useAmplitude();

  useEffect(() => {
    logEvent('event');
  }, [logEvent]);
}
```

the logEvent function will be a new function each render so the effect will trigger and `logEvent('event')` will be logged every render

**Comment by koblas** [comment]
When I look at `useAmplitude` it's using a useMemo function wrapper.  Which based on my understanding should return a consistent object for every call unless it's parameters change.

See -- 

   https://github.com/koblas/react-amplitude-hooks/blob/master/src/components/Amplitude.tsx
   
Can you provide any other details on why you think this is happening?

**Comment by ljmerza** [comment]
Yes I do see the useMemo. The example I gave above will prove this happens.

**Comment by koblas** [comment]
Given the fix is merged, let's close this
