### ISSUE TITLE
Version 0.10.2 is not available in NPM

### ISSUE THREAD

**Issue by thiagoboa** [koblas/react-amplitude-hooks#17]
Hi @koblas !

We were looking forward to install the latest version, 0.10.2, with the latest improvements, but it is yet not available in NPM:
https://www.npmjs.com/package/react-amplitude-hooks

![image](https://user-images.githubusercontent.com/22331895/126684765-9c8fc559-fff9-45c5-9790-4f62e779630d.png)

We would love to have access to it. Let me know if I can help with any thing.
Thanks in advance

**Comment by koblas** [comment]
I need to get my release processes with this project consistent with other projects I'm working on.  

Let's see if this works.

**Comment by koblas** [comment]
Bumping to 0.10.3 to fix the build disaster I accidentally created.
