### ISSUE TITLE
Missing Files in npm

### ISSUE THREAD

**Issue by arutr** [koblas/react-amplitude-hooks#3]
There don't seem to be any source files present in the latest version published on npm (`0.9.12`):
<img width="295" alt="Zrzut ekranu 2020-04-15 o 18 25 20" src="https://user-images.githubusercontent.com/10263999/79362111-783e2b80-7f46-11ea-8412-8615241467ac.png">

This is not the case with the previous version, `0.9.10`

**Comment by koblas** [comment]
Sorry about that.  Integrated a fix to have CircleCI do automated builds, but missed one piece of configuration.  

Please let me know if you're still having problems.
