### ISSUE TITLE
Where should I pass on userProperties?

### ISSUE THREAD

**Issue by eiriks** [koblas/react-amplitude-hooks#6]
react-amplitude-hooks provides four components and a hook. 

let's say I keep a set of attributes for a user: 

```
userProperties: {
    isLogedIn: true;
    hasPayedDues: false;
    otherPropertyThatCanChangeBetweenLoggedEvents: true;
}
```

`<AmplitudeProvider>` takes config, apiKey and userId (along the amplitude instance)

`<LogOnChange>` and `<LogOnMount>` takes the name of an event and eventProperties (and the value to track change in for LogOnChange).

`<Amplitude>` is the only component that takes the `userProperties` prop and thus lets us update attributes on the user? But that means render props patterns and not hook. Right?

{ logEvent } = useAmplitude() hook does not take userProperties.. 

Or do I misunderstand something?

Is there any way to use the hook from react-amplitude-hooks if I want to pass on updated userProperties?

**Comment by koblas** [comment]
I had to go back and look at the code and think about this.  Part of this is probably derived from being compatible with the original Amplitude API that they created.

The Amplitude API attaches the user props to the Instance tree.  So you really can't have 

```
<AmplitudeProvider>
   ...
      <Amplitude user=1> ... </Amplitude>
   ....
      <Amplitude user=2> ... </Amplitude>
   ....
</AmplitudeProvider>
```

When you think about that, it's pretty weird to have half a render tree with one user and the other half with a different user.  The rational I must have used when I put this together was that for a whole render tree you needed to have a single user, which would be set/updated on login.

```
<AmplitudeProvider>
    ...
   <AmplitudeUser>
       .. rest of tree ...
```
```
function AmplitudeUser({children}) { 
    // get the login user information format it for amplitude -- some hooky function
   return <Amplitude user=userInfo>{children}</Amplitude>
}
```

Or something like that -- more of a data state.

**Comment by eiriks** [comment]
Thanks to the feedback. 

The approach you suggested here, with wrapping the tree with another <AmplitudeUser> component that just does this "passing updated user props to amplitude" task, seems to work well. 

mine looks like this:
```
export const AmplitudeUser = (props: React.PropsWithChildren<any>) => {
    const { userProperties } = useUserProperties()!
    return <Amplitude userProperties={userProperties}>{props.children}</Amplitude>
}
```
 The http requests to amplitude gets this 
``` 
"user_properties":{"$set":{"registeredUser":true,"loggedIn":true,...}}
```

and I guess that the **"$set":** bit is attributes inherited from the amplitude instance (it is `"user_properties":{key:val,..}` when it is fired from <Amplitude> render props pattern).

It's working, anyway. And getting the updated userProperties it should. Thanks.
